// 前端 PoC 固定样例。金额、状态、模型与素材均不是服务端事实。
export const projects = [
  {
    id: "harbor",
    name: "雾港来信",
    subtitle: "一封迟到二十年的信，改变了这座城市。",
    style: "电影写实",
    aspect: "16:9",
    episodes: 3,
    progress: 42,
    status: "创作中",
    cover: "01",
  },
  {
    id: "summer",
    name: "夏日回声",
    subtitle: "穿过漫长夏天，找到属于自己的声音。",
    style: "清新动画",
    aspect: "9:16",
    episodes: 3,
    progress: 18,
    status: "创作中",
    cover: "02",
  },
  {
    id: "orbit",
    name: "第七次日出",
    subtitle: "轨道之外，还有未完成的约定。",
    style: "科幻写实",
    aspect: "16:9",
    episodes: 3,
    progress: 0,
    status: "草稿",
    cover: "03",
  },
] as const;
export const episodes = [
  {
    id: "ep-01",
    name: "第一集 · 雾中的访客",
    duration: "02:10",
    stages: ["已解析", "已锁定", "3 个镜头", "待生成", "待配音"],
  },
  {
    id: "ep-02",
    name: "第二集 · 旧日航线",
    duration: "02:30",
    stages: ["已解析", "缺少场景", "待拆分", "待生成", "待配音"],
  },
  {
    id: "ep-03",
    name: "第三集 · 天亮以前",
    duration: "02:00",
    stages: ["待解析", "待准备", "待拆分", "待生成", "待配音"],
  },
] as const;
export const shots = [
  {
    id: "shot-01",
    number: "01",
    title: "港口的第一道光",
    scene: "旧港码头",
    character: "林夏",
    camera: "远景",
    movement: "缓慢推进",
    duration: 5,
    status: "已有候选",
    prompt: "晨雾散开，林夏站在码头尽头。镜头缓慢推进，远处灯塔仍亮着。",
    dialogue: "这封信，是给我的？",
  },
  {
    id: "shot-02",
    number: "02",
    title: "信封上的旧名字",
    scene: "邮局内景",
    character: "林夏 / 老陈",
    camera: "特写",
    movement: "固定",
    duration: 4,
    status: "生成失败",
    prompt: "泛黄信封的特写，林夏的手指掠过字迹，背景是老旧邮局。",
    dialogue: "有些信，总会找到收信人。",
  },
  {
    id: "shot-03",
    number: "03",
    title: "沿海公路",
    scene: "海岸公路",
    character: "林夏",
    camera: "中景",
    movement: "跟随",
    duration: 6,
    status: "待生成",
    prompt: "林夏骑车驶向海岸。清晨柔和的光线，镜头从侧后方跟随。",
    dialogue: "我想去看看，那座灯塔。",
  },
] as const;
export const entities = {
  characters: [
    {
      id: "lin",
      name: "林夏",
      detail: "24 岁 · 邮局新职员 · 沉静、好奇",
      version: "v3",
      status: "已锁定",
    },
    {
      id: "chen",
      name: "老陈",
      detail: "61 岁 · 灯塔守望人 · 内敛",
      version: "v1",
      status: "待选定",
    },
  ],
  scenes: [
    {
      id: "port",
      name: "旧港码头",
      detail: "外景 · 清晨 · 雾与暖光",
      version: "v2",
      status: "已锁定",
    },
    {
      id: "post",
      name: "邮局内景",
      detail: "内景 · 白天 · 怀旧木质空间",
      version: "v1",
      status: "待选定",
    },
  ],
  props: [
    {
      id: "letter",
      name: "泛黄信封",
      detail: "剧情主线道具 · 旧邮戳",
      version: "v2",
      status: "已锁定",
    },
  ],
  voices: [
    {
      id: "voice-lin",
      name: "林夏 · 声音设定",
      detail: "温暖、自然 · 普通话 · 样例声线",
      version: "v1",
      status: "授权待核对",
    },
  ],
};
export const media = [
  {
    id: "media-01",
    name: "港口 · 关键帧 A",
    type: "image",
    origin: "生成产物",
    status: "审核通过",
    refs: 2,
  },
  {
    id: "media-02",
    name: "港口 · 关键帧 B",
    type: "image",
    origin: "生成产物",
    status: "审核通过",
    refs: 0,
  },
  {
    id: "media-03",
    name: "晨雾 · 视频预览",
    type: "video",
    origin: "内置样例",
    status: "审核通过",
    refs: 1,
  },
  {
    id: "media-04",
    name: "信封 · 参考素材",
    type: "image",
    origin: "上传样例",
    status: "审核中",
    refs: 1,
  },
];
export const tasks = [
  {
    id: "task-01",
    title: "镜头 01 · 关键帧",
    project: "雾港来信",
    state: "succeeded",
    label: "已完成",
    model: "图像模型 · 样例",
    cost: "¥1.20",
    time: "今天 10:42",
    detail: "产物已登记，可在镜头候选中查看。",
    action: "查看候选",
  },
  {
    id: "task-02",
    title: "镜头 02 · 视频",
    project: "雾港来信",
    state: "failed",
    label: "生成失败",
    model: "视频模型 · 样例",
    cost: "费用待核对",
    time: "今天 10:38",
    detail: "参考素材格式不满足模型要求。请调整引用与参数后重新报价。",
    action: "调整参数",
  },
  {
    id: "task-03",
    title: "镜头 03 · 视频",
    project: "雾港来信",
    state: "unknown",
    label: "提交结果未知",
    model: "视频模型 · 样例",
    cost: "费用待核对",
    time: "今天 10:35",
    detail:
      "提交响应超时，不能确认供应商是否已受理。应先核对供应商任务，不直接重复提交。",
    action: "查看核对说明",
  },
  {
    id: "task-04",
    title: "第一集 · 配音批次",
    project: "雾港来信",
    state: "partial",
    label: "部分失败",
    model: "语音模型 · 样例",
    cost: "¥0.60（样例）",
    time: "今天 10:30",
    detail:
      "3 条台词中 2 条完成，1 条声线授权待核对。只重新报价失败项，避免重复处理已完成台词。",
    action: "查看配音",
  },
];
export const budget = {
  limit_micros: 300000000,
  settled_micros: 42000000,
  reserved_micros: 18000000,
  available_micros: 240000000,
  is_overrun: false,
};
export const sourceScript = `第一集：雾中的访客\n\n场景 01 / 旧港码头 / 清晨\n晨雾散开，林夏站在码头尽头。远处的灯塔仍亮着。\n林夏：这封信，是给我的？\n\n场景 02 / 邮局内景 / 白天\n老陈递过一封泛黄的信。林夏低头看着熟悉的名字。\n老陈：有些信，总会找到收信人。\n\n场景 03 / 海岸公路 / 清晨\n林夏骑车驶向海岸，柔和的阳光穿过雾气。\n林夏：我想去看看，那座灯塔。`;
