import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/api/**", "src/lib/request.ts", "src/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "axios",
              message: "网络传输只允许在 src/lib/request.ts 中实现。",
            },
          ],
          patterns: [
            {
              group: ["**/request"],
              importNames: ["request"],
              message: "业务接口必须调用 src/api 中的自动生成函数。",
            },
            {
              group: ["@/gen/api", "@/gen/api/**"],
              message: "生成客户端统一位于 src/api。",
            },
          ],
        },
      ],
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message: "通过生成 API 或统一的媒体传输入口访问网络。",
        },
        {
          name: "XMLHttpRequest",
          message: "网络传输只允许在 request.ts 中实现。",
        },
        { name: "EventSource", message: "连接须由统一请求入口实现。" },
        { name: "WebSocket", message: "连接须由统一请求入口实现。" },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[property.name=/^(fetch|XMLHttpRequest|EventSource|WebSocket)$/]",
          message: "不得绕过统一请求入口访问网络。",
        },
        {
          selector:
            "MemberExpression[computed=true][property.value=/^(fetch|XMLHttpRequest|EventSource|WebSocket)$/]",
          message: "不得绕过统一请求入口访问网络。",
        },
        {
          selector: "Literal[value=/^\\u002Fapi(?:\\u002F|$)/]",
          message: "业务接口路径只能由 Umi OpenAPI 生成。",
        },
        {
          selector: "TemplateElement[value.raw=/^\\u002Fapi(?:\\u002F|$)/]",
          message: "业务接口路径只能由 Umi OpenAPI 生成。",
        },
      ],
    },
  },
  // These REST client files are generated by openapi2ts.
  {
    files: ["src/api/**/*.ts"],
    linterOptions: { reportUnusedDisableDirectives: "off" },
    rules: {
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
