[alembic]
script_location = %(here)s/migrations
prepend_sys_path = .
path_separator = newline
version_locations =
    %(here)s/migrations/identity/versions
    %(here)s/migrations/ingestion/versions
    %(here)s/migrations/catalog/versions
    %(here)s/migrations/search/versions
    %(here)s/migrations/creation/versions
    %(here)s/migrations/generation/versions
    %(here)s/migrations/asset/versions
    %(here)s/migrations/governance/versions
sqlalchemy.url =
