// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"net/http"

	"go.uber.org/zap"

	"github.com/StephenQiu30/lanverse/backend/internal/platform/config"
)

// Injectors from wire.go:

func initializeAPI(ctx context.Context, cfg config.Config, logger *zap.Logger) (*http.Server, func(), error) {
	tracerProvider, cleanup, err := provideTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideDB(ctx, cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisconnConnection, cleanup3, err := provideRedis(cfg, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	temporalconnConnection, cleanup4, err := provideTemporal(cfg, logger, tracerProvider)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, err := provideObjectStorage(cfg)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	readyCheck := provideReadyCheck(connection, redisconnConnection, temporalconnConnection, client)
	server := provideAPIServer(cfg, logger, readyCheck, tracerProvider)
	return server, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
