// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"net/http"

	"go.temporal.io/sdk/worker"
	"go.uber.org/zap"

	"github.com/StephenQiu30/lanverse/backend/internal/identity/application"
	"github.com/StephenQiu30/lanverse/backend/internal/infra/maintenance/adapter/temporal"
	"github.com/StephenQiu30/lanverse/backend/internal/operation/adapter/workflow"
	"github.com/StephenQiu30/lanverse/backend/internal/platform/config"

	_ "github.com/StephenQiu30/lanverse/backend/docs"
)

// Injectors from wire.go:

func initializeAPI(ctx context.Context, cfg config.Config, logger *zap.Logger) (*http.Server, func(), error) {
	tracerProvider, cleanup, err := provideTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideDB(ctx, cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisconnConnection, cleanup3, err := provideRedis(cfg, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	temporalconnConnection, cleanup4, err := provideTemporal(cfg, logger, tracerProvider)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, err := provideObjectStorage(cfg)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	readyCheck := provideReadyCheck(connection, redisconnConnection, temporalconnConnection, client)
	server, err := provideAPIServer(cfg, logger, readyCheck, tracerProvider, connection, redisconnConnection, client)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func initializeWorker(ctx context.Context, cfg config.Config, logger *zap.Logger, queue string) (worker.Worker, func(), error) {
	tracerProvider, cleanup, err := provideWorkerTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideDB(ctx, cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	temporalconnConnection, cleanup3, err := provideTemporal(cfg, logger, tracerProvider)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workerWorker, err := provideBackendWorker(ctx, cfg, connection, temporalconnConnection, queue)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return workerWorker, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func initializeRelay(ctx context.Context, cfg config.Config, logger *zap.Logger) (*relayRuntime, func(), error) {
	tracerProvider, cleanup, err := provideRelayTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideDB(ctx, cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kafkaconnConnection, cleanup3, err := provideKafka(ctx, cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisconnConnection, cleanup4, err := provideRedis(cfg, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appRelayRuntime, cleanup5, err := provideRelayRuntime(ctx, cfg, connection, kafkaconnConnection, redisconnConnection, logger, tracerProvider)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return appRelayRuntime, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func initializeMaintenanceSetup(ctx context.Context, cfg config.Config, logger *zap.Logger, prefix string) (*temporal.ScheduleInstaller, func(), error) {
	tracerProvider, cleanup, err := provideSetupTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideTemporal(cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	scheduleInstaller, err := provideCleanupScheduleInstaller(ctx, connection, prefix)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return scheduleInstaller, func() {
		cleanup2()
		cleanup()
	}, nil
}

func initializeQuoteExpirySetup(ctx context.Context, cfg config.Config, logger *zap.Logger, prefix string) (*workflow.QuoteExpiryScheduleInstaller, func(), error) {
	tracerProvider, cleanup, err := provideSetupTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideTemporal(cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	quoteExpiryScheduleInstaller, err := provideQuoteExpiryScheduleInstaller(ctx, connection, prefix)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return quoteExpiryScheduleInstaller, func() {
		cleanup2()
		cleanup()
	}, nil
}

func initializeAdminBootstrap(ctx context.Context, cfg config.Config, logger *zap.Logger) (*application.BootstrapAdminCommand, func(), error) {
	tracerProvider, cleanup, err := provideBootstrapTrace(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := provideDB(ctx, cfg, logger, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	store := provideIdentityStore(connection)
	bootstrapAdminCommand := provideBootstrapAdminCommand(store)
	return bootstrapAdminCommand, func() {
		cleanup2()
		cleanup()
	}, nil
}
