import type { components } from "./schema";

declare global {
  namespace API {
    type AuthResponse = components["schemas"]["AuthResponse"];
    type BibleEvidence = components["schemas"]["BibleEvidence"];
    type BibleReviewIssue = components["schemas"]["BibleReviewIssue"];
    type ChangePasswordRequest = components["schemas"]["ChangePasswordRequest"];
    type ConfirmEpisodePlanRequest = components["schemas"]["ConfirmEpisodePlanRequest"];
    type CostBudgetResponse = components["schemas"]["CostBudgetResponse"];
    type CostBudgetSetRequest = components["schemas"]["CostBudgetSetRequest"];
    type CostPriceQuoteResponse = components["schemas"]["CostPriceQuoteResponse"];
    type CostPriceQuoteSetRequest = components["schemas"]["CostPriceQuoteSetRequest"];
    type DeactivateAccountRequest = components["schemas"]["DeactivateAccountRequest"];
    type DocumentRevisionResponse = components["schemas"]["DocumentRevisionResponse"];
    type EpisodePlanCreateRequest = components["schemas"]["EpisodePlanCreateRequest"];
    type EpisodePlanDetailResponse = components["schemas"]["EpisodePlanDetailResponse"];
    type EpisodePlanImpactBlocker = components["schemas"]["EpisodePlanImpactBlocker"];
    type EpisodePlanImpactResponse = components["schemas"]["EpisodePlanImpactResponse"];
    type EpisodePlanResponse = components["schemas"]["EpisodePlanResponse"];
    type EpisodePlanSourceResponse = components["schemas"]["EpisodePlanSourceResponse"];
    type EpisodeProposalResponse = components["schemas"]["EpisodeProposalResponse"];
    type EpisodeResponse = components["schemas"]["EpisodeResponse"];
    type EpisodeSegmentOriginResponse = components["schemas"]["EpisodeSegmentOriginResponse"];
    type FormatIssueResponse = components["schemas"]["FormatIssueResponse"];
    type ImportCommitDetailResponse = components["schemas"]["ImportCommitDetailResponse"];
    type ImportCommitResponse = components["schemas"]["ImportCommitResponse"];
    type LoginRequest = components["schemas"]["LoginRequest"];
    type MaterializeEpisodePlanRequest = components["schemas"]["MaterializeEpisodePlanRequest"];
    type MeResponse = components["schemas"]["MeResponse"];
    type MediaObjectResponse = components["schemas"]["MediaObjectResponse"];
    type MediaVersionResponse = components["schemas"]["MediaVersionResponse"];
    type NarrativeBlockResponse = components["schemas"]["NarrativeBlockResponse"];
    type PaginatedProjects = components["schemas"]["PaginatedProjects"];
    type ProductionBibleConfirmRequest = components["schemas"]["ProductionBibleConfirmRequest"];
    type ProductionBibleCreateRequest = components["schemas"]["ProductionBibleCreateRequest"];
    type ProductionBibleEntityResponse = components["schemas"]["ProductionBibleEntityResponse"];
    type ProductionBibleEntityStateResponse = components["schemas"]["ProductionBibleEntityStateResponse"];
    type ProductionBibleResponse = components["schemas"]["ProductionBibleResponse"];
    type ProductionBibleResumeRequest = components["schemas"]["ProductionBibleResumeRequest"];
    type ProductionBibleWorldEntryResponse = components["schemas"]["ProductionBibleWorldEntryResponse"];
    type ProfileUpdateRequest = components["schemas"]["ProfileUpdateRequest"];
    type ProjectCreateRequest = components["schemas"]["ProjectCreateRequest"];
    type ProjectResponse = components["schemas"]["ProjectResponse"];
    type PublishImportCommitRequest = components["schemas"]["PublishImportCommitRequest"];
    type RegisterRequest = components["schemas"]["RegisterRequest"];
    type RegistrationVerificationAccepted = components["schemas"]["RegistrationVerificationAccepted"];
    type RegistrationVerificationConfirmRequest = components["schemas"]["RegistrationVerificationConfirmRequest"];
    type RegistrationVerificationConfirmed = components["schemas"]["RegistrationVerificationConfirmed"];
    type RegistrationVerificationRequest = components["schemas"]["RegistrationVerificationRequest"];
    type RevocationResponse = components["schemas"]["RevocationResponse"];
    type ScriptDocumentAnalysisResponse = components["schemas"]["ScriptDocumentAnalysisResponse"];
    type ScriptDocumentImportRequest = components["schemas"]["ScriptDocumentImportRequest"];
    type ScriptDocumentPreviewRequest = components["schemas"]["ScriptDocumentPreviewRequest"];
    type ScriptDocumentPreviewResponse = components["schemas"]["ScriptDocumentPreviewResponse"];
    type ScriptDocumentResponse = components["schemas"]["ScriptDocumentResponse"];
    type TaskErrorResponse = components["schemas"]["TaskErrorResponse"];
    type TaskResponse = components["schemas"]["TaskResponse"];
    type TaskScopeResponse = components["schemas"]["TaskScopeResponse"];
    type UploadCapabilityResponse = components["schemas"]["UploadCapabilityResponse"];
    type UploadCompletionResponse = components["schemas"]["UploadCompletionResponse"];
    type UploadDeclaration = components["schemas"]["UploadDeclaration"];
    type UploadInitializationResponse = components["schemas"]["UploadInitializationResponse"];
    type UploadSessionResponse = components["schemas"]["UploadSessionResponse"];
    type UserResponse = components["schemas"]["UserResponse"];
    type WorkflowControlEnvelope = components["schemas"]["WorkflowControlEnvelope"];
    type WorkflowControlIntentResponse = components["schemas"]["WorkflowControlIntentResponse"];
    type WorkflowControlRequest = components["schemas"]["WorkflowControlRequest"];
    type WorkflowNodeRunResponse = components["schemas"]["WorkflowNodeRunResponse"];
    type WorkflowRerunRequest = components["schemas"]["WorkflowRerunRequest"];
    type WorkflowRunEnvelope = components["schemas"]["WorkflowRunEnvelope"];
    type WorkflowRunResponse = components["schemas"]["WorkflowRunResponse"];
    type WorkflowRunViewResponse = components["schemas"]["WorkflowRunViewResponse"];
    type WorkflowStartRequest = components["schemas"]["WorkflowStartRequest"];
    type WorkspaceCreateRequest = components["schemas"]["WorkspaceCreateRequest"];
    type WorkspaceResponse = components["schemas"]["WorkspaceResponse"];
    type WorkspaceStateRequest = components["schemas"]["WorkspaceStateRequest"];
    type WorkspaceUpdateRequest = components["schemas"]["WorkspaceUpdateRequest"];
  }
}

export {};
