export const shotFixtures = [
  {
    id: "02-01",
    duration: "3.0s",
    mode: "图生视频",
    status: "已选定",
    video: "已选定",
    text: "远景，雨夜码头云雾缭绕。",
  },
  {
    id: "02-02",
    duration: "4.0s",
    mode: "图生视频",
    status: "已选定",
    video: "候选 2",
    text: "林舟停步走入画面，回头望向灯塔。",
  },
  {
    id: "02-03",
    duration: "2.0s",
    mode: "首尾帧",
    status: "已选定",
    video: "生成中",
    text: "特写，信封被雨打湿。",
  },
  {
    id: "02-04",
    duration: "4.0s",
    mode: "图生视频",
    status: "候选 2",
    video: "未生成",
    text: "中景推进，林舟在雨中抬头回望。冷色深水，背景灯塔虚焦。",
  },
  {
    id: "02-05",
    duration: "3.0s",
    mode: "全能参考",
    status: "生成中",
    video: "未生成",
    text: "反打，灯塔摇曳的光扫过雾面。",
  },
  {
    id: "02-06",
    duration: "5.0s",
    mode: "图生视频",
    status: "失败",
    video: "未生成",
    text: "雨中的旧码头，镜头缓慢拉远。",
  },
  {
    id: "02-07",
    duration: "3.0s",
    mode: "图生视频",
    status: "未生成",
    video: "未生成",
    text: "林舟低头查看信封。",
  },
  {
    id: "02-08",
    duration: "2.5s",
    mode: "首尾帧",
    status: "未生成",
    video: "未生成",
    text: "水面泛起微弱的涟漪。",
  },
  {
    id: "02-09",
    duration: "4.0s",
    mode: "全能参考",
    status: "生成中",
    video: "未生成",
    text: "汽笛响起，渔船驶离码头。",
  },
  {
    id: "02-10",
    duration: "3.5s",
    mode: "图生视频",
    status: "未生成",
    video: "未生成",
    text: "远处的灯塔在雾中渐渐消失。",
  },
];
