package media_test

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	a "github.com/StephenQiu30/lanverse/backend/internal/media/application"
	d "github.com/StephenQiu30/lanverse/backend/internal/media/domain"
)

// The fixture was generated by actual PrepareProjectMediaCopy at fixed 29ce5664,
// before library ownership or retained_history was introduced.
func TestProjectCopyLibraryNilFieldsPreserveActual29ceBytes(t *testing.T) {
	now := time.Date(2026, 10, 2, 3, 4, 5, 123456000, time.UTC)
	src := uuid.MustParse("11111111-1111-4111-8111-111111111111")
	id := uuid.MustParse("22222222-2222-4222-8222-222222222222")
	sha := strings.Repeat("b", 64)
	codec := "png"
	w, h := int32(3), int32(2)
	asset := d.MediaAsset{ID: id, ProjectID: src, Kind: d.KindImage, Origin: d.OriginUpload, Status: d.StatusReady, ObjectKey: "projects/" + src.String() + "/image/2026/10/" + id.String() + ".png", FileName: "旧项目.png", MimeType: "image/png", ByteSize: 88, SHA256: &sha, Width: &w, Height: &h, Codec: &codec, ModerationStatus: d.ModerationPassed, Revision: 1, CreateTime: now, UpdateTime: now}
	b := a.ProjectCopyBinding{JobID: uuid.MustParse("33333333-3333-4333-8333-333333333333"), OrgID: uuid.MustParse("44444444-4444-4444-8444-444444444444"), SourceProjectID: src, TargetProjectID: uuid.MustParse("55555555-5555-4555-8555-555555555555")}
	content, err := a.PrepareProjectMediaCopy(b, []a.ProjectCopySourceAsset{{Asset: asset}}, now)
	if err != nil {
		t.Fatal(err)
	}
	body, err := json.Marshal(struct {
		Source d.MediaAsset
		Copy   a.ProjectMediaCopy
	}{asset, content})
	if err != nil {
		t.Fatal(err)
	}
	expected, err := os.ReadFile("testdata/project_copy_29ce_library_golden.json")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(body, expected) {
		t.Fatal("legacy project/nil history JSON changed")
	}
}
