"""Add episode planning and batch materialization tables.

Revision ID: 7f3a9c1d2e84
Revises: 4c8e2f7a9b31
Create Date: 2026-08-13 11:51:30.336379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7f3a9c1d2e84"
down_revision: str | Sequence[str] | None = "4c8e2f7a9b31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scr_episode_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("document_revision_id", sa.Uuid(), nullable=False),
        sa.Column("strategy", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("target_duration_ms", sa.Integer(), nullable=False),
        sa.Column("requested_episode_count", sa.Integer(), nullable=True),
        sa.Column("total_estimated_duration_ms", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("planning_engine_version", sa.String(length=80), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("planning_task_id", sa.Uuid(), nullable=True),
        sa.Column("planning_error_code", sa.String(length=80), nullable=True),
        sa.Column("command_receipts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'review_ready', 'confirmed', 'materialized', 'superseded')",
            name="ck_scr_episode_plan_status",
        ),
        sa.CheckConstraint(
            "strategy IN ('explicit_markers', 'target_duration_ai')",
            name="ck_scr_episode_plan_strategy",
        ),
        sa.CheckConstraint(
            "requested_episode_count IS NULL OR "
            "(requested_episode_count >= 1 AND requested_episode_count <= 10)",
            name="ck_scr_episode_plan_requested_count",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_scr_episode_plan_revision"),
        sa.CheckConstraint("target_duration_ms >= 1000", name="ck_scr_episode_plan_duration"),
        sa.CheckConstraint(
            "total_estimated_duration_ms >= 0", name="ck_scr_episode_plan_total_duration"
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id", "workspace_id"],
            ["scr_document_revisions.id", "scr_document_revisions.workspace_id"],
            name="fk_scr_episode_plan_revision_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["planning_task_id", "workspace_id"],
            ["prod_tasks.id", "prod_tasks.workspace_id"],
            name="fk_scr_episode_plan_task_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["prj_projects.id", "prj_projects.workspace_id"],
            name="fk_scr_episode_plan_project_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_episode_plan_id_workspace"),
        sa.UniqueConstraint(
            "project_id", "idempotency_key", name="uq_scr_episode_plan_project_idempotency"
        ),
    )
    op.create_index(
        "ix_scr_episode_plan_revision_status_created",
        "scr_episode_plans",
        ["document_revision_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "scr_episode_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("start_block_id", sa.Uuid(), nullable=False),
        sa.Column("end_block_id", sa.Uuid(), nullable=False),
        sa.Column("start_block_position", sa.Integer(), nullable=False),
        sa.Column("end_block_position", sa.Integer(), nullable=False),
        sa.Column("source_start", sa.Integer(), nullable=False),
        sa.Column("source_end", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("estimated_duration_ms", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("boundary_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_scr_episode_proposal_confidence"
        ),
        sa.CheckConstraint(
            "end_block_position >= start_block_position", name="ck_scr_episode_proposal_block_range"
        ),
        sa.CheckConstraint(
            "estimated_duration_ms >= 1000", name="ck_scr_episode_proposal_duration"
        ),
        sa.CheckConstraint("position >= 1", name="ck_scr_episode_proposal_position"),
        sa.CheckConstraint(
            "source_end > source_start", name="ck_scr_episode_proposal_source_range"
        ),
        sa.CheckConstraint("source_start >= 0", name="ck_scr_episode_proposal_source_start"),
        sa.CheckConstraint(
            "start_block_position >= 1", name="ck_scr_episode_proposal_start_block_position"
        ),
        sa.ForeignKeyConstraint(
            ["end_block_id", "workspace_id"],
            ["scr_narrative_blocks.id", "scr_narrative_blocks.workspace_id"],
            name="fk_scr_episode_proposal_end_block_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "workspace_id"],
            ["scr_episode_plans.id", "scr_episode_plans.workspace_id"],
            name="fk_scr_episode_proposal_plan_workspace",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["start_block_id", "workspace_id"],
            ["scr_narrative_blocks.id", "scr_narrative_blocks.workspace_id"],
            name="fk_scr_episode_proposal_start_block_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_episode_proposal_id_workspace"),
        sa.UniqueConstraint("plan_id", "position", name="uq_scr_episode_proposal_plan_position"),
    )
    op.create_index(
        "ix_scr_episode_proposal_plan_range",
        "scr_episode_proposals",
        ["plan_id", "source_start"],
        unique=False,
    )
    op.create_table(
        "scr_import_commits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("expected_project_revision", sa.Integer(), nullable=False),
        sa.Column("expected_active_order_hash", sa.String(length=64), nullable=False),
        sa.Column("result_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("publish_input_hash", sa.String(length=64), nullable=True),
        sa.Column("publish_idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mode IN ('append_new')", name="ck_scr_import_commit_mode"),
        sa.CheckConstraint(
            "status IN ('pending', 'materializing', 'materialized', 'publishing', "
            "'published', 'conflict', 'failed')",
            name="ck_scr_import_commit_status",
        ),
        sa.CheckConstraint(
            "expected_project_revision >= 1", name="ck_scr_import_commit_project_revision"
        ),
        sa.CheckConstraint("revision >= 1", name="ck_scr_import_commit_revision"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "workspace_id"],
            ["scr_episode_plans.id", "scr_episode_plans.workspace_id"],
            name="fk_scr_import_commit_plan_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["prj_projects.id", "prj_projects.workspace_id"],
            name="fk_scr_import_commit_project_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_import_commit_id_workspace"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_scr_import_commit_workspace_idempotency"
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "publish_idempotency_key",
            name="uq_scr_import_commit_publish_idempotency",
        ),
    )
    op.create_index(
        "ix_scr_import_commit_plan_created",
        "scr_import_commits",
        ["plan_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "scr_episode_segment_origins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("import_commit_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("document_revision_id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("draft_version_id", sa.Uuid(), nullable=False),
        sa.Column("published_version_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_start", sa.Integer(), nullable=False),
        sa.Column("source_end", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 1", name="ck_scr_segment_origin_position"),
        sa.CheckConstraint("source_end > source_start", name="ck_scr_segment_origin_source_range"),
        sa.CheckConstraint("source_start >= 0", name="ck_scr_segment_origin_source_start"),
        sa.ForeignKeyConstraint(
            ["document_revision_id", "workspace_id"],
            ["scr_document_revisions.id", "scr_document_revisions.workspace_id"],
            name="fk_scr_segment_origin_revision_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["draft_version_id", "workspace_id"],
            ["scr_script_versions.id", "scr_script_versions.workspace_id"],
            name="fk_scr_segment_origin_draft_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["episode_id", "workspace_id"],
            ["prj_episodes.id", "prj_episodes.workspace_id"],
            name="fk_scr_segment_origin_episode_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["import_commit_id", "workspace_id"],
            ["scr_import_commits.id", "scr_import_commits.workspace_id"],
            name="fk_scr_segment_origin_commit_workspace",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id", "workspace_id"],
            ["scr_episode_proposals.id", "scr_episode_proposals.workspace_id"],
            name="fk_scr_segment_origin_proposal_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["published_version_id", "workspace_id"],
            ["scr_script_versions.id", "scr_script_versions.workspace_id"],
            name="fk_scr_segment_origin_published_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "workspace_id"],
            ["scr_script_sources.id", "scr_script_sources.workspace_id"],
            name="fk_scr_segment_origin_source_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_segment_origin_id_workspace"),
        sa.UniqueConstraint(
            "import_commit_id", "episode_id", name="uq_scr_segment_origin_commit_episode"
        ),
        sa.UniqueConstraint(
            "import_commit_id", "position", name="uq_scr_segment_origin_commit_position"
        ),
    )
    op.create_index(
        "ix_scr_segment_origin_revision_range",
        "scr_episode_segment_origins",
        ["document_revision_id", "source_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scr_segment_origin_revision_range", table_name="scr_episode_segment_origins")
    op.drop_table("scr_episode_segment_origins")
    op.drop_index("ix_scr_import_commit_plan_created", table_name="scr_import_commits")
    op.drop_table("scr_import_commits")
    op.drop_index("ix_scr_episode_proposal_plan_range", table_name="scr_episode_proposals")
    op.drop_table("scr_episode_proposals")
    op.drop_index("ix_scr_episode_plan_revision_status_created", table_name="scr_episode_plans")
    op.drop_table("scr_episode_plans")
    # ### end Alembic commands ###
