"""建立当前模型基线

Revision ID: 95c0d24572c5
Revises:
Create Date: 2026-08-13 00:38:01.311204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "95c0d24572c5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idn_user_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'deactivated')", name="ck_idn_user_status"),
        sa.CheckConstraint("token_version >= 1", name="ck_idn_user_token_version"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_normalized"),
    )
    op.create_index(
        op.f("ix_idn_user_accounts_status"), "idn_user_accounts", ["status"], unique=False
    )
    op.create_table(
        "idn_workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_idn_workspace_status"),
        sa.CheckConstraint("revision >= 1", name="ck_idn_workspace_revision"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_idn_workspaces_status"), "idn_workspaces", ["status"], unique=False)
    op.create_table(
        "prod_model_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("input_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameter_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pricing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("unavailable_reason", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('text', 'image', 'video')", name="ck_prod_capability_kind"),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'unavailable')", name="ck_prod_capability_status"
        ),
        sa.CheckConstraint("config_version >= 1", name="ck_prod_capability_config_version"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "config_version", name="uq_prod_capability_id_version"),
        sa.UniqueConstraint(
            "provider", "model", "kind", "config_version", name="uq_prod_capability_configuration"
        ),
    )
    op.create_index(
        "ix_prod_capability_kind_status",
        "prod_model_capabilities",
        ["kind", "status"],
        unique=False,
    )
    op.create_table(
        "gov_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=60), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "result IN ('succeeded', 'denied', 'failed')", name="ck_gov_audit_result"
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gov_audit_workspace_action_occurred",
        "gov_audit_events",
        ["workspace_id", "action", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_gov_audit_workspace_actor_occurred",
        "gov_audit_events",
        ["workspace_id", "actor_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_gov_audit_workspace_occurred",
        "gov_audit_events",
        ["workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_gov_audit_workspace_target_occurred",
        "gov_audit_events",
        ["workspace_id", "target_type", "target_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "gov_consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("subject_identity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject_type", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'revoked')", name="ck_gov_consent_status"
        ),
        sa.CheckConstraint(
            "subject_type IN ('SCRIPT_VERSION', 'ASSET_VERSION', "
            "'SHOT_SPEC_VERSION', 'CANDIDATE', 'MEDIA_VERSION', "
            "'TIMELINE_VERSION', 'DELIVERY')",
            name="ck_gov_consent_subject_type",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_gov_consent_revision"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id", "workspace_id"],
            ["gov_consent_revisions.id", "gov_consent_revisions.workspace_id"],
            name="fk_gov_consent_current_revision_workspace",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_gov_consent_id_workspace"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_gov_consent_workspace_idempotency"
        ),
    )
    op.create_index(
        "ix_gov_consent_workspace_status_updated",
        "gov_consents",
        ["workspace_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_gov_consent_workspace_subject",
        "gov_consents",
        ["workspace_id", "subject_type", "subject_id"],
        unique=False,
    )
    op.create_table(
        "idn_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name="ck_idn_membership_role"),
        sa.CheckConstraint("status IN ('active', 'removed')", name="ck_idn_membership_status"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_idn_membership_workspace_user"),
    )
    op.create_table(
        "med_media_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('image', 'video', 'audio', 'subtitle', 'delivery')",
            name="ck_med_media_object_kind",
        ),
        sa.CheckConstraint(
            "source_type IN ('upload', 'generated', 'rendered')", name="ck_med_media_object_source"
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_med_media_object_status"),
        sa.CheckConstraint("revision >= 1", name="ck_med_media_object_revision"),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id", "workspace_id"],
            ["med_media_versions.id", "med_media_versions.workspace_id"],
            name="fk_med_object_current_version_workspace",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_med_object_id_workspace"),
    )
    op.create_index(
        "ix_med_object_workspace_kind_status_created",
        "med_media_objects",
        ["workspace_id", "kind", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "med_upload_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("media_object_id", sa.Uuid(), nullable=True),
        sa.Column("expected_current_version_id", sa.Uuid(), nullable=True),
        sa.Column("storage_profile", sa.String(length=80), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("declared_kind", sa.String(length=30), nullable=False),
        sa.Column("declared_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("declared_mime_type", sa.String(length=120), nullable=False),
        sa.Column("declared_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("completed_version_id", sa.Uuid(), nullable=True),
        sa.Column("completed_probe_task_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "declared_kind IN ('image', 'video', 'audio', 'subtitle', 'delivery')",
            name="ck_med_upload_kind",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'expired', 'failed')", name="ck_med_upload_status"
        ),
        sa.CheckConstraint("declared_size_bytes >= 1", name="ck_med_upload_size"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "storage_profile", "bucket", "object_key", name="uq_med_upload_physical_object"
        ),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_med_upload_idempotency"),
    )
    op.create_index(
        "ix_med_upload_workspace_status_expiry",
        "med_upload_sessions",
        ["workspace_id", "status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "prj_projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("aspect_ratio", sa.String(length=10), nullable=False),
        sa.Column("language", sa.String(length=35), nullable=False),
        sa.Column("visual_style", sa.String(length=200), nullable=True),
        sa.Column("target_duration_ms", sa.Integer(), nullable=False),
        sa.Column("budget_limit", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_prj_project_status"),
        sa.CheckConstraint("budget_limit >= 0", name="ck_prj_project_budget"),
        sa.CheckConstraint("revision >= 1", name="ck_prj_project_revision"),
        sa.CheckConstraint("target_duration_ms > 0", name="ck_prj_project_duration"),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prj_project_id_workspace"),
    )
    op.create_index(
        "ix_prj_project_workspace_status_updated",
        "prj_projects",
        ["workspace_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "prod_provider_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("preset_id", sa.String(length=100), nullable=False),
        sa.Column("catalog_version", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("protocol", sa.String(length=40), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("non_secret_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("configuration_status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "configuration_status IN ('incomplete', 'valid', 'invalid')",
            name="ck_prod_provider_connection_configuration",
        ),
        sa.CheckConstraint(
            "protocol IN ('openai_compatible', 'anthropic_native', 'gemini_native', 'ark_native')",
            name="ck_prod_provider_connection_protocol",
        ),
        sa.CheckConstraint("catalog_version >= 1", name="ck_prod_provider_connection_catalog"),
        sa.CheckConstraint("revision >= 1", name="ck_prod_provider_connection_revision"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prod_provider_connection_id_workspace"),
    )
    op.create_index(
        "ix_prod_provider_connection_workspace_archived",
        "prod_provider_connections",
        ["workspace_id", "archived_at"],
        unique=False,
    )
    op.create_table(
        "prod_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=True),
        sa.Column("render_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("usage_type", sa.String(length=50), nullable=True),
        sa.Column("usage_id", sa.Uuid(), nullable=True),
        sa.Column("input_version_id", sa.Uuid(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("progress_stage", sa.String(length=50), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("next_action", sa.String(length=80), nullable=True),
        sa.Column("cancel_status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cancel_status IN ('none', 'requested', 'accepted', 'rejected')",
            name="ck_prod_task_cancel_status",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting_provider', "
            "'succeeded', 'failed', 'cancelled', 'unknown')",
            name="ck_prod_task_status",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_prod_task_revision"),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prod_task_id_workspace"),
        sa.UniqueConstraint(
            "workspace_id", "task_type", "idempotency_key", name="uq_prod_task_idempotency"
        ),
    )
    op.create_index(
        "ix_prod_task_workspace_status_created",
        "prod_tasks",
        ["workspace_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "sys_outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("routing_key", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("traceparent", sa.String(length=55), nullable=False),
        sa.Column("causation_event_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=100), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'published', 'manual_attention')",
            name="ck_sys_outbox_status",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_sys_outbox_attempt_count"),
        sa.CheckConstraint("schema_version >= 1", name="ck_sys_outbox_schema_version"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_type", "aggregate_id", "schema_version", name="uq_sys_outbox_aggregate_event"
        ),
        sa.UniqueConstraint("id", "workspace_id", name="uq_sys_outbox_id_workspace"),
    )
    op.create_index(
        "ix_sys_outbox_publishable", "sys_outbox_events", ["status", "available_at"], unique=False
    )
    op.create_table(
        "sys_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_key", sa.String(length=200), nullable=False),
        sa.Column("handler_name", sa.String(length=100), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("misfire_policy", sa.String(length=20), nullable=False),
        sa.Column("max_catch_up", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("leased_by", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('one_off', 'interval', 'cron')", name="ck_sys_schedule_kind"),
        sa.CheckConstraint(
            "misfire_policy IN ('skip', 'run_once', 'catch_up')",
            name="ck_sys_schedule_misfire_policy",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'completed', 'manual_attention')",
            name="ck_sys_schedule_status",
        ),
        sa.CheckConstraint("failure_count >= 0", name="ck_sys_schedule_failure_count"),
        sa.CheckConstraint("max_catch_up >= 0", name="ck_sys_schedule_max_catch_up"),
        sa.CheckConstraint("revision >= 1", name="ck_sys_schedule_revision"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_sys_schedule_id_workspace"),
        sa.UniqueConstraint("workspace_id", "schedule_key", name="uq_sys_schedule_workspace_key"),
    )
    op.create_index(
        "ix_sys_schedule_due",
        "sys_schedules",
        ["status", "next_fire_at", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "ast_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('character', 'location', 'prop', 'costume', 'visual_style', 'voice')",
            name="ck_ast_asset_kind",
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_ast_asset_status"),
        sa.CheckConstraint("revision >= 1", name="ck_ast_asset_revision"),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id", "workspace_id"],
            ["ast_asset_versions.id", "ast_asset_versions.workspace_id"],
            name="fk_ast_asset_current_version_workspace",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["prj_projects.id", "prj_projects.workspace_id"],
            name="fk_ast_asset_project_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_ast_asset_id_workspace"),
    )
    op.create_index(
        "ix_ast_asset_project_kind_normalized_name",
        "ast_assets",
        ["project_id", "kind", "normalized_name"],
        unique=False,
    )
    op.create_index(
        "ix_ast_asset_project_kind_status",
        "ast_assets",
        ["project_id", "kind", "status"],
        unique=False,
    )
    op.create_table(
        "gov_consent_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('register', 'update', 'revoke')", name="ck_gov_revision_action"
        ),
        sa.CheckConstraint("revision_no >= 1", name="ck_gov_revision_number"),
        sa.CheckConstraint("valid_to > valid_from", name="ck_gov_revision_validity"),
        sa.ForeignKeyConstraint(
            ["consent_id", "workspace_id"],
            ["gov_consents.id", "gov_consents.workspace_id"],
            name="fk_gov_revision_consent_workspace",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consent_id", "revision_no", name="uq_gov_revision_consent_number"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_gov_revision_id_workspace"),
    )
    op.create_index(
        "ix_gov_revision_consent_created",
        "gov_consent_revisions",
        ["consent_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "med_media_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("media_object_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("probe_status", sa.String(length=20), nullable=False),
        sa.Column("probe_attempt", sa.Integer(), nullable=False),
        sa.Column("probe_task_id", sa.Uuid(), nullable=True),
        sa.Column("probe_idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("probe_error_code", sa.String(length=80), nullable=True),
        sa.Column("probe_error_summary", sa.Text(), nullable=True),
        sa.Column("probe_next_action", sa.String(length=80), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("codec", sa.String(length=120), nullable=True),
        sa.Column("container", sa.String(length=120), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "probe_status IN ('pending', 'ready', 'failed', 'quarantined')",
            name="ck_med_version_probe_status",
        ),
        sa.CheckConstraint("probe_attempt >= 1", name="ck_med_version_probe_attempt"),
        sa.CheckConstraint("size_bytes >= 1", name="ck_med_version_size"),
        sa.CheckConstraint("version_no >= 1", name="ck_med_version_number"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id", "workspace_id"],
            ["med_media_objects.id", "med_media_objects.workspace_id"],
            name="fk_med_version_object_workspace",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_med_version_id_workspace"),
        sa.UniqueConstraint("media_object_id", "version_no", name="uq_med_version_object_number"),
    )
    op.create_index("ix_med_version_sha256", "med_media_versions", ["sha256"], unique=False)
    op.create_index(
        "ix_med_version_workspace_created",
        "med_media_versions",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "prj_episodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("target_duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("current_script_version_id", sa.Uuid(), nullable=True),
        sa.Column("current_timeline_version_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_prj_episode_status"),
        sa.CheckConstraint("position >= 1", name="ck_prj_episode_position"),
        sa.CheckConstraint("revision >= 1", name="ck_prj_episode_revision"),
        sa.CheckConstraint("target_duration_ms > 0", name="ck_prj_episode_duration"),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["prj_projects.id", "prj_projects.workspace_id"],
            name="fk_prj_episode_project_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prj_episode_id_workspace"),
    )
    op.create_index(
        "ix_prj_episode_project_status_position",
        "prj_episodes",
        ["project_id", "status", "position"],
        unique=False,
    )
    op.create_index(
        "uq_prj_episode_active_position",
        "prj_episodes",
        ["project_id", "position"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "prod_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("provider_request_key", sa.String(length=64), nullable=False),
        sa.Column("provider_task_id", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("request_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("reconcile_summary", sa.Text(), nullable=True),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('prepared', 'submitting', 'accepted', 'polling', "
            "'succeeded', 'failed', 'cancelled', 'unknown')",
            name="ck_prod_attempt_status",
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_prod_attempt_sequence"),
        sa.ForeignKeyConstraint(
            ["task_id", "workspace_id"],
            ["prod_tasks.id", "prod_tasks.workspace_id"],
            name="fk_prod_attempt_task_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prod_attempt_id_workspace"),
        sa.UniqueConstraint("provider_request_key", name="uq_prod_attempt_provider_request_key"),
        sa.UniqueConstraint("task_id", "sequence", name="uq_prod_attempt_task_sequence"),
    )
    op.create_index(
        "ix_prod_attempt_workspace_status",
        "prod_attempts",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "prod_provider_credential_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(length=100), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("auth_tag", sa.LargeBinary(), nullable=False),
        sa.Column("fingerprint_hmac", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('current', 'retiring', 'revoked')",
            name="ck_prod_provider_credential_status",
        ),
        sa.CheckConstraint(
            "char_length(fingerprint_hmac) = 64", name="ck_prod_provider_credential_fingerprint"
        ),
        sa.CheckConstraint(
            "octet_length(auth_tag) = 16", name="ck_prod_provider_credential_auth_tag"
        ),
        sa.CheckConstraint(
            "octet_length(ciphertext) > 0", name="ck_prod_provider_credential_ciphertext"
        ),
        sa.CheckConstraint("octet_length(nonce) = 12", name="ck_prod_provider_credential_nonce"),
        sa.CheckConstraint("version >= 1", name="ck_prod_provider_credential_version"),
        sa.ForeignKeyConstraint(
            ["connection_id", "workspace_id"],
            ["prod_provider_connections.id", "prod_provider_connections.workspace_id"],
            name="fk_prod_provider_credential_connection_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "fingerprint_hmac",
            name="uq_prod_provider_credential_connection_fingerprint",
        ),
        sa.UniqueConstraint(
            "connection_id", "version", name="uq_prod_provider_credential_connection_version"
        ),
        sa.UniqueConstraint(
            "id", "workspace_id", "connection_id", name="uq_prod_provider_credential_identity"
        ),
    )
    op.create_index(
        "ix_prod_provider_credential_workspace_created",
        "prod_provider_credential_versions",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_prod_provider_credential_current",
        "prod_provider_credential_versions",
        ["connection_id"],
        unique=True,
        postgresql_where=sa.text("status = 'current'"),
    )
    op.create_table(
        "sys_inbox_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("consumer_name", sa.String(length=100), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'rejected', "
            "'retry_scheduled', 'manual_attention')",
            name="ck_sys_inbox_status",
        ),
        sa.CheckConstraint("attempt_count >= 1", name="ck_sys_inbox_attempt_count"),
        sa.ForeignKeyConstraint(
            ["task_id", "workspace_id"],
            ["prod_tasks.id", "prod_tasks.workspace_id"],
            name="fk_sys_inbox_task_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "consumer_name", name="uq_sys_inbox_event_consumer"),
    )
    op.create_index(
        "ix_sys_inbox_status_received",
        "sys_inbox_deliveries",
        ["status", "received_at"],
        unique=False,
    )
    op.create_table(
        "sys_schedule_fires",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("fire_key", sa.String(length=200), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger_kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("outbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('dispatched')", name="ck_sys_schedule_fire_status"),
        sa.CheckConstraint(
            "trigger_kind IN ('scheduled', 'manual')", name="ck_sys_schedule_fire_trigger_kind"
        ),
        sa.ForeignKeyConstraint(
            ["outbox_event_id", "workspace_id"],
            ["sys_outbox_events.id", "sys_outbox_events.workspace_id"],
            name="fk_sys_schedule_fire_outbox_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id", "workspace_id"],
            ["sys_schedules.id", "sys_schedules.workspace_id"],
            name="fk_sys_schedule_fire_schedule_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "workspace_id"],
            ["prod_tasks.id", "prod_tasks.workspace_id"],
            name="fk_sys_schedule_fire_task_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "fire_key", name="uq_sys_schedule_fire_key"),
    )
    op.create_index(
        "ix_sys_schedule_fire_schedule_created",
        "sys_schedule_fires",
        ["schedule_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ast_asset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_description", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('manual', 'candidate')", name="ck_ast_version_source_type"
        ),
        sa.CheckConstraint("schema_version >= 1", name="ck_ast_schema_version"),
        sa.CheckConstraint("version_no >= 1", name="ck_ast_version_number"),
        sa.ForeignKeyConstraint(
            ["asset_id", "workspace_id"],
            ["ast_assets.id", "ast_assets.workspace_id"],
            name="fk_ast_version_asset_workspace",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "version_no", name="uq_ast_version_number"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_ast_version_id_workspace"),
        sa.UniqueConstraint("source_type", "source_id", name="uq_ast_version_source"),
    )
    op.create_index(
        "ix_ast_version_content_hash", "ast_asset_versions", ["content_hash"], unique=False
    )
    op.create_table(
        "gov_consent_proofs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("consent_revision_id", sa.Uuid(), nullable=False),
        sa.Column("media_version_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 1", name="ck_gov_proof_position"),
        sa.ForeignKeyConstraint(
            ["consent_revision_id", "workspace_id"],
            ["gov_consent_revisions.id", "gov_consent_revisions.workspace_id"],
            name="fk_gov_proof_revision_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["media_version_id", "workspace_id"],
            ["med_media_versions.id", "med_media_versions.workspace_id"],
            name="fk_gov_proof_media_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "consent_revision_id", "media_version_id", name="uq_gov_proof_revision_media"
        ),
        sa.UniqueConstraint(
            "consent_revision_id", "position", name="uq_gov_proof_revision_position"
        ),
    )
    op.create_index("ix_gov_proof_media", "gov_consent_proofs", ["media_version_id"], unique=False)
    op.create_table(
        "med_media_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("media_version_id", sa.Uuid(), nullable=False),
        sa.Column("storage_profile", sa.String(length=80), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("migration_task_id", sa.Uuid(), nullable=True),
        sa.Column("retire_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('verified', 'active', 'retiring', 'retired', 'quarantined')",
            name="ck_med_location_status",
        ),
        sa.ForeignKeyConstraint(
            ["media_version_id", "workspace_id"],
            ["med_media_versions.id", "med_media_versions.workspace_id"],
            name="fk_med_location_version_workspace",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "storage_profile", "bucket", "object_key", name="uq_med_location_physical_object"
        ),
    )
    op.create_index(
        "uq_med_location_active_version",
        "med_media_locations",
        ["media_version_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "prod_provider_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("usage_type", sa.String(length=40), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("credential_version_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("capability_config_version", sa.Integer(), nullable=False),
        sa.Column("binding_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("activated_by", sa.Uuid(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deactivated_by", sa.Uuid(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'active' AND deactivated_by IS NULL "
            "AND deactivated_at IS NULL) OR (status = 'inactive' "
            "AND deactivated_by IS NOT NULL AND deactivated_at IS NOT NULL)",
            name="ck_prod_provider_binding_lifecycle",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name="ck_prod_provider_binding_status"
        ),
        sa.CheckConstraint(
            "usage_type IN ('script_structure', 'image_generation', 'video_generation')",
            name="ck_prod_provider_binding_usage",
        ),
        sa.CheckConstraint("binding_revision >= 1", name="ck_prod_provider_binding_revision"),
        sa.CheckConstraint(
            "capability_config_version >= 1", name="ck_prod_provider_binding_capability_version"
        ),
        sa.ForeignKeyConstraint(
            ["activated_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["capability_id", "capability_config_version"],
            ["prod_model_capabilities.id", "prod_model_capabilities.config_version"],
            name="fk_prod_provider_binding_capability_version",
        ),
        sa.ForeignKeyConstraint(
            ["credential_version_id", "workspace_id", "connection_id"],
            [
                "prod_provider_credential_versions.id",
                "prod_provider_credential_versions.workspace_id",
                "prod_provider_credential_versions.connection_id",
            ],
            name="fk_prod_provider_binding_credential_identity",
        ),
        sa.ForeignKeyConstraint(
            ["deactivated_by"],
            ["idn_user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prod_provider_binding_id_workspace"),
    )
    op.create_index(
        "ix_prod_provider_binding_connection_status",
        "prod_provider_bindings",
        ["connection_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_prod_provider_binding_active_usage",
        "prod_provider_bindings",
        ["workspace_id", "usage_type"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "prod_provider_health_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("connection_revision", sa.Integer(), nullable=False),
        sa.Column("credential_version_id", sa.Uuid(), nullable=False),
        sa.Column("probe_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("safe_error_code", sa.String(length=80), nullable=True),
        sa.Column("checked_by", sa.Uuid(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "probe_type IN ('model_discovery', 'metadata')",
            name="ck_prod_provider_health_probe_type",
        ),
        sa.CheckConstraint(
            "status IN ('healthy', 'degraded', 'unreachable')",
            name="ck_prod_provider_health_status",
        ),
        sa.CheckConstraint(
            "connection_revision >= 1", name="ck_prod_provider_health_connection_revision"
        ),
        sa.CheckConstraint("expires_at > checked_at", name="ck_prod_provider_health_expiry"),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0", name="ck_prod_provider_health_latency"
        ),
        sa.ForeignKeyConstraint(
            ["checked_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["credential_version_id", "workspace_id", "connection_id"],
            [
                "prod_provider_credential_versions.id",
                "prod_provider_credential_versions.workspace_id",
                "prod_provider_credential_versions.connection_id",
            ],
            name="fk_prod_provider_health_credential_identity",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_prod_provider_health_connection_checked",
        "prod_provider_health_checks",
        ["connection_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "sbd_shot_transforms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("source_shot_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("source_spec_version_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("result_shot_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("impact_hash", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "operation IN ('copy', 'split', 'merge')", name="ck_sbd_transform_operation"
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id", "workspace_id"],
            ["prj_episodes.id", "prj_episodes.workspace_id"],
            name="fk_sbd_transform_episode_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["idn_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_sbd_transform_workspace_idempotency"
        ),
    )
    op.create_index(
        "ix_sbd_transform_episode_created",
        "sbd_shot_transforms",
        ["episode_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sbd_transform_input_hash", "sbd_shot_transforms", ["input_hash"], unique=False
    )
    op.create_table(
        "scr_script_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("input_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("source_media_version_id", sa.Uuid(), nullable=True),
        sa.Column("rights_declaration", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("input_type IN ('text', 'media')", name="ck_scr_source_input_type"),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_scr_source_status"),
        sa.CheckConstraint("revision >= 1", name="ck_scr_source_revision"),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id", "workspace_id"],
            ["prj_episodes.id", "prj_episodes.workspace_id"],
            name="fk_scr_source_episode_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "episode_id", "idempotency_key", name="uq_scr_source_episode_idempotency"
        ),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_source_id_workspace"),
    )
    op.create_index(
        "ix_scr_source_episode_status", "scr_script_sources", ["episode_id", "status"], unique=False
    )
    op.create_table(
        "ast_media_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("asset_version_id", sa.Uuid(), nullable=False),
        sa.Column("media_version_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 1", name="ck_ast_media_ref_position"),
        sa.ForeignKeyConstraint(
            ["asset_version_id", "workspace_id"],
            ["ast_asset_versions.id", "ast_asset_versions.workspace_id"],
            name="fk_ast_media_ref_version_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["media_version_id", "workspace_id"],
            ["med_media_versions.id", "med_media_versions.workspace_id"],
            name="fk_ast_media_ref_media_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "asset_version_id", "purpose", "position", name="uq_ast_media_ref_purpose_position"
        ),
    )
    op.create_index(
        "ix_ast_media_ref_media", "ast_media_references", ["media_version_id"], unique=False
    )
    op.create_table(
        "scr_script_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("structure_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('draft', 'published')", name="ck_scr_version_status"),
        sa.CheckConstraint("version_no >= 1", name="ck_scr_version_number"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "workspace_id"],
            ["scr_script_sources.id", "scr_script_sources.workspace_id"],
            name="fk_scr_version_source_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_version_id_workspace"),
        sa.UniqueConstraint("source_id", "version_no", name="uq_scr_version_number"),
    )
    op.create_index(
        "ix_scr_version_content_hash", "scr_script_versions", ["content_hash"], unique=False
    )
    op.create_table(
        "scr_extraction_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("extractor_version", sa.String(length=80), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confirmed_script_version_id", sa.Uuid(), nullable=True),
        sa.Column("result_hash", sa.String(length=64), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope = 'full'", name="ck_scr_batch_scope"),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting_provider', "
            "'succeeded', 'failed', 'cancelled', 'unknown')",
            name="ck_scr_batch_status",
        ),
        sa.CheckConstraint("candidate_count >= 0", name="ck_scr_batch_candidate_count"),
        sa.ForeignKeyConstraint(
            ["confirmed_script_version_id", "workspace_id"],
            ["scr_script_versions.id", "scr_script_versions.workspace_id"],
            name="fk_scr_batch_confirmed_version_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["script_version_id", "workspace_id"],
            ["scr_script_versions.id", "scr_script_versions.workspace_id"],
            name="fk_scr_batch_version_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "workspace_id"],
            ["prod_tasks.id", "prod_tasks.workspace_id"],
            name="fk_scr_batch_task_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_batch_id_workspace"),
        sa.UniqueConstraint(
            "script_version_id", "idempotency_key", name="uq_scr_batch_version_idempotency"
        ),
        sa.UniqueConstraint("task_id", name="uq_scr_batch_task"),
    )
    op.create_index(
        "ix_scr_batch_workspace_status_created",
        "scr_extraction_batches",
        ["workspace_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "scr_scenes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("time_of_day", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_start", sa.Integer(), nullable=False),
        sa.Column("source_end", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 1", name="ck_scr_scene_position"),
        sa.CheckConstraint("source_end > source_start", name="ck_scr_scene_source_range"),
        sa.CheckConstraint("source_start >= 0", name="ck_scr_scene_source_start"),
        sa.ForeignKeyConstraint(
            ["script_version_id", "workspace_id"],
            ["scr_script_versions.id", "scr_script_versions.workspace_id"],
            name="fk_scr_scene_version_workspace",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_scene_id_workspace"),
        sa.UniqueConstraint("script_version_id", "position", name="uq_scr_scene_version_position"),
    )
    op.create_index(
        "ix_scr_scene_version_range",
        "scr_scenes",
        ["script_version_id", "source_start"],
        unique=False,
    )
    op.create_table(
        "scr_dialogues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("speaker_candidate", sa.String(length=200), nullable=False),
        sa.Column("dialogue_kind", sa.String(length=30), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("performance_note", sa.Text(), nullable=True),
        sa.Column("source_start", sa.Integer(), nullable=False),
        sa.Column("source_end", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "dialogue_kind IN ('spoken', 'narration', 'internal', 'voice_over')",
            name="ck_scr_dialogue_kind",
        ),
        sa.CheckConstraint("position >= 1", name="ck_scr_dialogue_position"),
        sa.CheckConstraint("source_end > source_start", name="ck_scr_dialogue_source_range"),
        sa.CheckConstraint("source_start >= 0", name="ck_scr_dialogue_source_start"),
        sa.ForeignKeyConstraint(
            ["scene_id", "workspace_id"],
            ["scr_scenes.id", "scr_scenes.workspace_id"],
            name="fk_scr_dialogue_scene_workspace",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_dialogue_id_workspace"),
        sa.UniqueConstraint("scene_id", "position", name="uq_scr_dialogue_scene_position"),
    )
    op.create_index(
        "ix_scr_dialogue_scene_range", "scr_dialogues", ["scene_id", "source_start"], unique=False
    )
    op.create_table(
        "scr_extraction_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_key", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("source_start", sa.Integer(), nullable=False),
        sa.Column("source_end", sa.Integer(), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_note", sa.Text(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('scene', 'dialogue', 'asset', 'shot', 'continuity')",
            name="ck_scr_candidate_kind",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'linked', 'merged', 'ignored')",
            name="ck_scr_candidate_status",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_scr_candidate_revision"),
        sa.CheckConstraint("source_end > source_start", name="ck_scr_candidate_source_range"),
        sa.CheckConstraint("source_start >= 0", name="ck_scr_candidate_source_start"),
        sa.ForeignKeyConstraint(
            ["batch_id", "workspace_id"],
            ["scr_extraction_batches.id", "scr_extraction_batches.workspace_id"],
            name="fk_scr_candidate_batch_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "candidate_key", name="uq_scr_candidate_batch_key"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_scr_candidate_id_workspace"),
    )
    op.create_index(
        "ix_scr_candidate_batch_status_range",
        "scr_extraction_candidates",
        ["batch_id", "status", "source_start", "source_end"],
        unique=False,
    )
    op.create_table(
        "sbd_shots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source_script_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_scene_id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("creation_key", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_spec_version_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_sbd_shot_status"),
        sa.CheckConstraint("position >= 1", name="ck_sbd_shot_position"),
        sa.CheckConstraint("revision >= 1", name="ck_sbd_shot_revision"),
        sa.ForeignKeyConstraint(
            ["archived_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_spec_version_id", "workspace_id"],
            ["sbd_shot_spec_versions.id", "sbd_shot_spec_versions.workspace_id"],
            name="fk_sbd_shot_current_spec_workspace",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["episode_id", "workspace_id"],
            ["prj_episodes.id", "prj_episodes.workspace_id"],
            name="fk_sbd_shot_episode_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id", "workspace_id"],
            ["scr_extraction_candidates.id", "scr_extraction_candidates.workspace_id"],
            name="fk_sbd_shot_candidate_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["source_scene_id", "workspace_id"],
            ["scr_scenes.id", "scr_scenes.workspace_id"],
            name="fk_sbd_shot_scene_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["source_script_version_id", "workspace_id"],
            ["scr_script_versions.id", "scr_script_versions.workspace_id"],
            name="fk_sbd_shot_script_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_sbd_shot_id_workspace"),
        sa.UniqueConstraint(
            "workspace_id", "creation_key", name="uq_sbd_shot_workspace_creation_key"
        ),
    )
    op.create_index(
        "ix_sbd_shot_episode_status_position",
        "sbd_shots",
        ["episode_id", "status", "position"],
        unique=False,
    )
    op.create_index(
        "ix_sbd_shot_script_scene",
        "sbd_shots",
        ["source_script_version_id", "source_scene_id"],
        unique=False,
    )
    op.create_index(
        "uq_sbd_shot_active_position",
        "sbd_shots",
        ["episode_id", "position"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_sbd_shot_workspace_candidate",
        "sbd_shots",
        ["workspace_id", "source_candidate_id"],
        unique=True,
        postgresql_where=sa.text("source_candidate_id IS NOT NULL"),
    )
    op.create_table(
        "scr_candidate_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("decision_key", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("downstream_type", sa.String(length=40), nullable=True),
        sa.Column("downstream_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('accept_new', 'accept_with_changes', 'link_existing', "
            "'merge_into', 'ignore')",
            name="ck_scr_decision_action",
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_scr_decision_sequence"),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id", "workspace_id"],
            ["scr_extraction_candidates.id", "scr_extraction_candidates.workspace_id"],
            name="fk_scr_decision_candidate_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "decision_key", name="uq_scr_decision_candidate_key"),
        sa.UniqueConstraint("candidate_id", "sequence", name="uq_scr_decision_candidate_sequence"),
    )
    op.create_index(
        "ix_scr_decision_candidate_created",
        "scr_candidate_decisions",
        ["candidate_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sbd_shot_spec_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("schema_version = 1", name="ck_sbd_spec_schema_version"),
        sa.CheckConstraint("version_no >= 1", name="ck_sbd_spec_version_number"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shot_id", "workspace_id"],
            ["sbd_shots.id", "sbd_shots.workspace_id"],
            name="fk_sbd_spec_shot_workspace",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_sbd_spec_id_workspace"),
        sa.UniqueConstraint("shot_id", "version_no", name="uq_sbd_spec_version_number"),
    )
    op.create_index(
        "ix_sbd_spec_input_hash", "sbd_shot_spec_versions", ["input_hash"], unique=False
    )
    op.create_table(
        "prod_generation_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("shot_spec_version_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("capability_config_version", sa.Integer(), nullable=False),
        sa.Column("parameter_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "warning_acknowledgements", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("shot_spec_input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("preflight_hash", sa.String(length=64), nullable=False),
        sa.Column("preflight_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("high_cost_confirmed", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "capability_config_version >= 1", name="ck_prod_request_capability_version"
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["prod_model_capabilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id", "workspace_id"],
            ["prj_episodes.id", "prj_episodes.workspace_id"],
            name="fk_prod_request_episode_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["prj_projects.id", "prj_projects.workspace_id"],
            name="fk_prod_request_project_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["idn_user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shot_id", "workspace_id"],
            ["sbd_shots.id", "sbd_shots.workspace_id"],
            name="fk_prod_request_shot_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["shot_spec_version_id", "workspace_id"],
            ["sbd_shot_spec_versions.id", "sbd_shot_spec_versions.workspace_id"],
            name="fk_prod_request_spec_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prod_request_id_workspace"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_prod_request_workspace_idempotency"
        ),
    )
    op.create_index(
        "ix_prod_request_input_hash", "prod_generation_requests", ["input_hash"], unique=False
    )
    op.create_index(
        "ix_prod_request_project_created",
        "prod_generation_requests",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_prod_request_shot_created",
        "prod_generation_requests",
        ["shot_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sbd_asset_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("shot_spec_version_id", sa.Uuid(), nullable=False),
        sa.Column("slot_key", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("asset_version_id", sa.Uuid(), nullable=False),
        sa.Column("subject_key", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('location', 'character', 'prop', 'costume', 'visual_style', 'voice')",
            name="ck_sbd_asset_ref_role",
        ),
        sa.ForeignKeyConstraint(
            ["asset_version_id", "workspace_id"],
            ["ast_asset_versions.id", "ast_asset_versions.workspace_id"],
            name="fk_sbd_asset_ref_version_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["shot_spec_version_id", "workspace_id"],
            ["sbd_shot_spec_versions.id", "sbd_shot_spec_versions.workspace_id"],
            name="fk_sbd_asset_ref_spec_workspace",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shot_spec_version_id", "slot_key", name="uq_sbd_asset_ref_spec_slot"),
    )
    op.create_index(
        "ix_sbd_asset_ref_asset_version", "sbd_asset_references", ["asset_version_id"], unique=False
    )
    op.create_table(
        "prod_generation_request_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("asset_version_id", sa.Uuid(), nullable=False),
        sa.Column("slot_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_version_id", "workspace_id"],
            ["ast_asset_versions.id", "ast_asset_versions.workspace_id"],
            name="fk_prod_request_asset_version_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["request_id", "workspace_id"],
            ["prod_generation_requests.id", "prod_generation_requests.workspace_id"],
            name="fk_prod_request_asset_request_workspace",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "slot_key", name="uq_prod_request_asset_slot"),
    )
    op.create_index(
        "ix_prod_request_asset_version",
        "prod_generation_request_assets",
        ["asset_version_id"],
        unique=False,
    )
    op.create_table(
        "prod_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("estimated_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'settled', 'released')", name="ck_prod_reservation_status"
        ),
        sa.CheckConstraint("estimated_amount >= 0", name="ck_prod_reservation_estimated"),
        sa.CheckConstraint("reserved_amount >= 0", name="ck_prod_reservation_reserved"),
        sa.CheckConstraint("revision >= 1", name="ck_prod_reservation_revision"),
        sa.ForeignKeyConstraint(
            ["request_id", "workspace_id"],
            ["prod_generation_requests.id", "prod_generation_requests.workspace_id"],
            name="fk_prod_reservation_request_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_prod_reservation_id_workspace"),
        sa.UniqueConstraint("request_id", name="uq_prod_reservation_request"),
    )
    op.create_index(
        "ix_prod_reservation_workspace_status",
        "prod_reservations",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "prod_cost_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider_bill_ref", sa.String(length=200), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('reserve', 'settle', 'release', 'adjust')",
            name="ck_prod_cost_entry_type",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id", "workspace_id"],
            ["prod_attempts.id", "prod_attempts.workspace_id"],
            name="fk_prod_cost_attempt_workspace",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id", "workspace_id"],
            ["prod_reservations.id", "prod_reservations.workspace_id"],
            name="fk_prod_cost_reservation_workspace",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reservation_id", "idempotency_key", name="uq_prod_cost_entry_idempotency"
        ),
    )
    op.create_index(
        "ix_prod_cost_reservation_created",
        "prod_cost_entries",
        ["reservation_id", "created_at"],
        unique=False,
    )
    # SQLAlchemy's use_alter relationships are intentionally omitted from
    # CREATE TABLE until both sides exist. Alembic autogenerate renders the
    # metadata marker but does not emit the required ALTER statements for an
    # initial revision, so the four current pointers must be created explicitly.
    op.create_foreign_key(
        "fk_gov_consent_current_revision_workspace",
        "gov_consents",
        "gov_consent_revisions",
        ["current_revision_id", "workspace_id"],
        ["id", "workspace_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_med_object_current_version_workspace",
        "med_media_objects",
        "med_media_versions",
        ["current_version_id", "workspace_id"],
        ["id", "workspace_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_ast_asset_current_version_workspace",
        "ast_assets",
        "ast_asset_versions",
        ["current_version_id", "workspace_id"],
        ["id", "workspace_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_sbd_shot_current_spec_workspace",
        "sbd_shots",
        "sbd_shot_spec_versions",
        ["current_spec_version_id", "workspace_id"],
        ["id", "workspace_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_sbd_shot_current_spec_workspace", "sbd_shots", type_="foreignkey")
    op.drop_constraint("fk_ast_asset_current_version_workspace", "ast_assets", type_="foreignkey")
    op.drop_constraint(
        "fk_med_object_current_version_workspace",
        "med_media_objects",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_gov_consent_current_revision_workspace",
        "gov_consents",
        type_="foreignkey",
    )
    op.drop_index("ix_prod_cost_reservation_created", table_name="prod_cost_entries")
    op.drop_table("prod_cost_entries")
    op.drop_index("ix_prod_reservation_workspace_status", table_name="prod_reservations")
    op.drop_table("prod_reservations")
    op.drop_index("ix_prod_request_asset_version", table_name="prod_generation_request_assets")
    op.drop_table("prod_generation_request_assets")
    op.drop_index("ix_sbd_asset_ref_asset_version", table_name="sbd_asset_references")
    op.drop_table("sbd_asset_references")
    op.drop_index("ix_prod_request_shot_created", table_name="prod_generation_requests")
    op.drop_index("ix_prod_request_project_created", table_name="prod_generation_requests")
    op.drop_index("ix_prod_request_input_hash", table_name="prod_generation_requests")
    op.drop_table("prod_generation_requests")
    op.drop_index("ix_sbd_spec_input_hash", table_name="sbd_shot_spec_versions")
    op.drop_table("sbd_shot_spec_versions")
    op.drop_index("ix_scr_decision_candidate_created", table_name="scr_candidate_decisions")
    op.drop_table("scr_candidate_decisions")
    op.drop_index(
        "uq_sbd_shot_workspace_candidate",
        table_name="sbd_shots",
        postgresql_where=sa.text("source_candidate_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_sbd_shot_active_position",
        table_name="sbd_shots",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_sbd_shot_script_scene", table_name="sbd_shots")
    op.drop_index("ix_sbd_shot_episode_status_position", table_name="sbd_shots")
    op.drop_table("sbd_shots")
    op.drop_index("ix_scr_candidate_batch_status_range", table_name="scr_extraction_candidates")
    op.drop_table("scr_extraction_candidates")
    op.drop_index("ix_scr_dialogue_scene_range", table_name="scr_dialogues")
    op.drop_table("scr_dialogues")
    op.drop_index("ix_scr_scene_version_range", table_name="scr_scenes")
    op.drop_table("scr_scenes")
    op.drop_index("ix_scr_batch_workspace_status_created", table_name="scr_extraction_batches")
    op.drop_table("scr_extraction_batches")
    op.drop_index("ix_scr_version_content_hash", table_name="scr_script_versions")
    op.drop_table("scr_script_versions")
    op.drop_index("ix_ast_media_ref_media", table_name="ast_media_references")
    op.drop_table("ast_media_references")
    op.drop_index("ix_scr_source_episode_status", table_name="scr_script_sources")
    op.drop_table("scr_script_sources")
    op.drop_index("ix_sbd_transform_input_hash", table_name="sbd_shot_transforms")
    op.drop_index("ix_sbd_transform_episode_created", table_name="sbd_shot_transforms")
    op.drop_table("sbd_shot_transforms")
    op.drop_index(
        "ix_prod_provider_health_connection_checked", table_name="prod_provider_health_checks"
    )
    op.drop_table("prod_provider_health_checks")
    op.drop_index(
        "uq_prod_provider_binding_active_usage",
        table_name="prod_provider_bindings",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_prod_provider_binding_connection_status", table_name="prod_provider_bindings")
    op.drop_table("prod_provider_bindings")
    op.drop_index(
        "uq_med_location_active_version",
        table_name="med_media_locations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("med_media_locations")
    op.drop_index("ix_gov_proof_media", table_name="gov_consent_proofs")
    op.drop_table("gov_consent_proofs")
    op.drop_index("ix_ast_version_content_hash", table_name="ast_asset_versions")
    op.drop_table("ast_asset_versions")
    op.drop_index("ix_sys_schedule_fire_schedule_created", table_name="sys_schedule_fires")
    op.drop_table("sys_schedule_fires")
    op.drop_index("ix_sys_inbox_status_received", table_name="sys_inbox_deliveries")
    op.drop_table("sys_inbox_deliveries")
    op.drop_index(
        "uq_prod_provider_credential_current",
        table_name="prod_provider_credential_versions",
        postgresql_where=sa.text("status = 'current'"),
    )
    op.drop_index(
        "ix_prod_provider_credential_workspace_created",
        table_name="prod_provider_credential_versions",
    )
    op.drop_table("prod_provider_credential_versions")
    op.drop_index("ix_prod_attempt_workspace_status", table_name="prod_attempts")
    op.drop_table("prod_attempts")
    op.drop_index(
        "uq_prj_episode_active_position",
        table_name="prj_episodes",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_prj_episode_project_status_position", table_name="prj_episodes")
    op.drop_table("prj_episodes")
    op.drop_index("ix_med_version_workspace_created", table_name="med_media_versions")
    op.drop_index("ix_med_version_sha256", table_name="med_media_versions")
    op.drop_table("med_media_versions")
    op.drop_index("ix_gov_revision_consent_created", table_name="gov_consent_revisions")
    op.drop_table("gov_consent_revisions")
    op.drop_index("ix_ast_asset_project_kind_status", table_name="ast_assets")
    op.drop_index("ix_ast_asset_project_kind_normalized_name", table_name="ast_assets")
    op.drop_table("ast_assets")
    op.drop_index("ix_sys_schedule_due", table_name="sys_schedules")
    op.drop_table("sys_schedules")
    op.drop_index("ix_sys_outbox_publishable", table_name="sys_outbox_events")
    op.drop_table("sys_outbox_events")
    op.drop_index("ix_prod_task_workspace_status_created", table_name="prod_tasks")
    op.drop_table("prod_tasks")
    op.drop_index(
        "ix_prod_provider_connection_workspace_archived", table_name="prod_provider_connections"
    )
    op.drop_table("prod_provider_connections")
    op.drop_index("ix_prj_project_workspace_status_updated", table_name="prj_projects")
    op.drop_table("prj_projects")
    op.drop_index("ix_med_upload_workspace_status_expiry", table_name="med_upload_sessions")
    op.drop_table("med_upload_sessions")
    op.drop_index("ix_med_object_workspace_kind_status_created", table_name="med_media_objects")
    op.drop_table("med_media_objects")
    op.drop_table("idn_memberships")
    op.drop_index("ix_gov_consent_workspace_subject", table_name="gov_consents")
    op.drop_index("ix_gov_consent_workspace_status_updated", table_name="gov_consents")
    op.drop_table("gov_consents")
    op.drop_index("ix_gov_audit_workspace_target_occurred", table_name="gov_audit_events")
    op.drop_index("ix_gov_audit_workspace_occurred", table_name="gov_audit_events")
    op.drop_index("ix_gov_audit_workspace_actor_occurred", table_name="gov_audit_events")
    op.drop_index("ix_gov_audit_workspace_action_occurred", table_name="gov_audit_events")
    op.drop_table("gov_audit_events")
    op.drop_index("ix_prod_capability_kind_status", table_name="prod_model_capabilities")
    op.drop_table("prod_model_capabilities")
    op.drop_index(op.f("ix_idn_workspaces_status"), table_name="idn_workspaces")
    op.drop_table("idn_workspaces")
    op.drop_index(op.f("ix_idn_user_accounts_status"), table_name="idn_user_accounts")
    op.drop_table("idn_user_accounts")
    # ### end Alembic commands ###
