root = "/src"
tmp_dir = "/tmp/lanverse-air"
env_files = []

[build]
cmd = "go build -p 2 -o /tmp/lanverse-air/lanverse ./cmd/lanverse"
entrypoint = ["/tmp/lanverse-air/lanverse"]
include_ext = ["go"]
include_dir = ["cmd", "internal", "docs"]
include_file = ["go.mod", "go.sum"]
exclude_dir = ["tests", "docker"]
exclude_regex = ["_test\\.go$"]
poll = true
poll_interval = 2000
delay = 500
stop_on_error = true
send_interrupt = true
kill_delay = "30s"
rerun = true
rerun_delay = 3000

[log]
time = true

[misc]
clean_on_exit = true

[screen]
keep_scroll = true
