from __future__ import annotations

EXPECTED_OPERATIONS = {
    ("createProject", "post", "/v1/projects"),
    ("listProjects", "get", "/v1/projects"),
    ("getProject", "get", "/v1/projects/{project_id}"),
    ("getEpisode", "get", "/v1/episodes/{episode_id}"),
    ("createSourceRevision", "post", "/v1/episodes/{episode_id}/sources"),
    ("confirmSource", "post", "/v1/source-revisions/{version_id}:confirm"),
    ("listSourceRevisions", "get", "/v1/episodes/{episode_id}/source-revisions"),
    ("getSourceRevision", "get", "/v1/source-revisions/{version_id}"),
    ("listTasks", "get", "/v1/tasks"),
    ("getTask", "get", "/v1/tasks/{task_id}"),
    ("cancelTask", "post", "/v1/tasks/{task_id}:cancel"),
    ("retryTask", "post", "/v1/tasks/{task_id}:retry"),
    ("generateScript", "post", "/v1/episodes/{episode_id}/script-generations"),
    ("getCurrentScript", "get", "/v1/episodes/{episode_id}/script"),
    ("saveScript", "put", "/v1/script-versions/{version_id}"),
    ("confirmScript", "post", "/v1/script-versions/{version_id}:confirm"),
    ("deriveScriptDraft", "post", "/v1/script-versions/{version_id}/drafts"),
    ("listScriptVersions", "get", "/v1/episodes/{episode_id}/script-versions"),
    ("getScriptVersion", "get", "/v1/script-versions/{version_id}"),
    ("listCreativeAssets", "get", "/v1/episodes/{episode_id}/creative-assets"),
    ("getCreativeAssetVersion", "get", "/v1/creative-asset-versions/{version_id}"),
    ("saveCreativeAsset", "put", "/v1/creative-asset-versions/{version_id}"),
    ("generateStoryboard", "post", "/v1/episodes/{episode_id}/storyboard-generations"),
    ("getStoryboard", "get", "/v1/episodes/{episode_id}/storyboard"),
    ("saveStoryboard", "put", "/v1/shot-spec-versions/{version_id}"),
    ("confirmStoryboard", "post", "/v1/shot-spec-versions/{version_id}:confirm"),
    ("deriveStoryboardDraft", "post", "/v1/shot-spec-versions/{version_id}/drafts"),
    ("listStoryboardVersions", "get", "/v1/episodes/{episode_id}/shot-spec-versions"),
    ("getStoryboardVersion", "get", "/v1/shot-spec-versions/{version_id}"),
    ("generateMedia", "post", "/v1/episodes/{episode_id}/media-generations"),
    ("listCandidates", "get", "/v1/episodes/{episode_id}/candidates"),
    (
        "authorizeCandidatePreview",
        "post",
        "/v1/media-versions/{media_version_id}/preview-authorizations",
    ),
    ("adoptCandidate", "post", "/v1/adoptions"),
    ("createSubtitles", "post", "/v1/episodes/{episode_id}/subtitle-versions"),
    ("getSubtitles", "get", "/v1/episodes/{episode_id}/subtitles"),
    ("saveSubtitles", "put", "/v1/subtitle-versions/{version_id}"),
    ("listSubtitleVersions", "get", "/v1/episodes/{episode_id}/subtitle-versions"),
    ("getSubtitleVersion", "get", "/v1/subtitle-versions/{version_id}"),
    ("deriveSubtitleDraft", "post", "/v1/subtitle-versions/{version_id}/drafts"),
    ("confirmSubtitles", "post", "/v1/subtitle-versions/{version_id}:confirm"),
    ("renderEpisode", "post", "/v1/episodes/{episode_id}/renders"),
    ("listDeliveries", "get", "/v1/episodes/{episode_id}/deliveries"),
    ("getDelivery", "get", "/v1/deliveries/{delivery_id}"),
    ("authorizeDownload", "post", "/v1/deliveries/{delivery_id}/download-authorizations"),
}
